// <auto-generated />
using System;
using CampFes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
#nullable disable
namespace CampFes.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241021-171327_AddRoleColumn")]
    partial class AddRoleColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("CampFes.Models.CheckPoint", b =>
                {
                    b.Property<int>("CID")
                        .HasColumnType("int");
                    b.Property<DateTime?>("CREATE_TIME")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasComment("建立時間");
                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("說明");
                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("名稱");
                    b.Property<int>("QFLAG")
                        .HasColumnType("int")
                        .HasComment("大地遊戲用為1 否則為0");
                    b.Property<string>("QRCODE")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasComment("QRCODE條碼");
                    b.Property<DateTime?>("UPDATE_TIME")
                        .HasColumnType("datetime")
                        .HasComment("更新時間");
                    b.HasKey("CID");
                    b.ToTable("CheckPoint");
                });
            modelBuilder.Entity("CampFes.Models.Login.AllUsers", b =>
                {
                    b.Property<string>("AREA")
                        .HasColumnType("varchar(10)")
                        .HasComment("營位");
                    b.Property<string>("CHECKER")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("報到代表人");
                    b.Property<string>("NICK_NAME")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("暱稱");
                    b.Property<string>("ROLE")
                        .HasColumnType("varchar(10)")
                        .HasComment("權限角色");
                    b.ToTable("AllUsers");
                });
            modelBuilder.Entity("CampFes.Models.Login.AllowPlayer", b =>
                {
                    b.Property<string>("IS_STAFF")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasComment("是否是工作人員");
                    b.Property<string>("NICK_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("暱稱");
                    b.Property<string>("REMARK")
                        .HasColumnType("nvarchar(100)")
                        .HasComment("備註");
                    b.Property<string>("UNI_QRCODE")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasComment("電子身分證");
                    b.ToTable("AllowPlayer");
                });
            modelBuilder.Entity("CampFes.Models.Login.EasyUser", b =>
                {
                    b.Property<int>("UID")
                        .HasColumnType("int");
                    b.Property<DateTime?>("CREATE_TIME")
                        .HasColumnType("datetime")
                        .HasComment("建立時間");
                    b.Property<string>("FINGERPRINT")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasComment("手機指紋");
                    b.Property<string>("IS_LOGIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasComment("是否登入中");
                    b.Property<string>("IS_RECIEVED")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasComment("領取紀錄");
                    b.Property<string>("NICK_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasComment("暱稱");
                    b.Property<int?>("PID")
                        .HasColumnType("int")
                        .HasComment("闖關獎品編號");
                    b.Property<string>("REMARK")
                        .HasColumnType("nvarchar(100)")
                        .HasComment("備註");
                    b.Property<string>("ROLE")
                        .HasColumnType("varchar(10)")
                        .HasComment("權限角色");
                    b.Property<string>("UNI_QRCODE")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasComment("電子身分證");
                    b.HasKey("UID");
                    b.ToTable("EasyUser");
                });
            modelBuilder.Entity("CampFes.Models.Login.Role", b =>
                {
                    b.Property<string>("ROLE")
                        .HasColumnType("varchar(20)")
                        .HasComment("角色");
                    b.Property<string>("HAS_PRIZE")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasComment("是否有參加獎");
                    b.Property<int>("LEVEL")
                        .HasColumnType("int")
                        .HasComment("權限等級");
                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("名稱");
                    b.HasKey("ROLE");
                    b.ToTable("Role");
                });
            modelBuilder.Entity("CampFes.Models.Lottery.Prize", b =>
                {
                    b.Property<int>("PID")
                        .HasColumnType("int");
                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(100)")
                        .HasComment("說明");
                    b.Property<string>("GRADING")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasComment("等級");
                    b.Property<int?>("QUANTITY")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasComment("數量");
                    b.Property<string>("REMARK")
                        .HasColumnType("nvarchar(200)")
                        .HasComment("備註");
                    b.HasKey("PID");
                    b.ToTable("Prize");
                });
            modelBuilder.Entity("CampFes.Models.Quest.QuestHistory", b =>
                {
                    b.Property<int>("UID")
                        .HasColumnType("int")
                        .HasComment("用戶 UID");
                    b.Property<int>("QNO")
                        .HasColumnType("int")
                        .HasComment("問題序號1~10");
                    b.Property<string>("ANSWER")
                        .HasColumnType("varchar(4)")
                        .HasComment("答題");
                    b.Property<int>("CID")
                        .HasColumnType("int")
                        .HasComment("QRCODE CID");
                    b.Property<DateTime?>("END_TIME")
                        .HasColumnType("datetime")
                        .HasComment("答題結束時間");
                    b.Property<int?>("QID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasComment("題目 QID");
                    b.Property<int?>("SPEND_SECONDS")
                        .HasColumnType("int")
                        .HasComment("耗費秒數");
                    b.Property<DateTime?>("START_TIME")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("答題起始時間");
                    b.HasKey("UID", "QNO");
                    b.ToTable("QuestHistory");
                });
            modelBuilder.Entity("CampFes.Models.Quest.Question", b =>
                {
                    b.Property<int>("QID")
                        .HasColumnType("int");
                    b.Property<string>("AUTHOR")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("出題者");
                    b.Property<string>("CORRECT")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasComment("答案");
                    b.Property<string>("HINT")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("提示");
                    b.Property<string>("IS_MULTI")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasComment("是否為複選題");
                    b.Property<string>("IS_USE")
                        .HasColumnType("varchar(1)")
                        .HasComment("是否採用");
                    b.Property<string>("OPTION_A")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("選項A");
                    b.Property<string>("OPTION_B")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("選項B");
                    b.Property<string>("OPTION_C")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("選項C");
                    b.Property<string>("OPTION_D")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("選項D");
                    b.Property<string>("QUESTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("問題");
                    b.HasKey("QID");
                    b.ToTable("Question");
                });
            modelBuilder.Entity("CampFes.Models.Regis.Registration", b =>
                {
                    b.Property<int>("RID")
                        .HasColumnType("int");
                    b.Property<string>("AREA")
                        .HasColumnType("varchar(10)")
                        .HasComment("營位");
                    b.Property<string>("CHECKER")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("實際報到人");
                    b.Property<string>("IS_RECIEVED")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasComment("領取紀錄");
                    b.Property<string>("ITEMS")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("領取品");
                    b.Property<string>("NICK_NAMES")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasComment("報到人暱稱(可多人)");
                    b.Property<string>("PHONES")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)")
                        .HasComment("報到人手機(可多組)");
                    b.Property<string>("REMARK")
                        .HasColumnType("nvarchar(200)")
                        .HasComment("備註");
                    b.Property<DateTime?>("UPDATE_TIME")
                        .HasColumnType("datetime")
                        .HasComment("更新時間");
                    b.HasKey("RID");
                    b.ToTable("Registration");
                });
            modelBuilder.Entity("CampFes.Models.System.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));
                    b.Property<string>("CALLSITE")
                        .HasColumnType("varchar(max)");
                    b.Property<string>("EXCETION")
                        .HasColumnType("varchar(max)");
                    b.Property<string>("LOGGER")
                        .HasColumnType("varchar(100)");
                    b.Property<string>("LOGLEVEL")
                        .HasColumnType("varchar(50)");
                    b.Property<string>("MACHINE_NAME")
                        .HasColumnType("varchar(100)");
                    b.Property<string>("MESSAGE")
                        .HasColumnType("varchar(max)");
                    b.Property<string>("TIMESTAMP")
                        .HasColumnType("varchar(50)");
                    b.HasKey("ID");
                    b.ToTable("ErrorLog");
                });
#pragma warning restore 612, 618
        }
    }
}
